=pod

=head1 NAME

B<ads> - commandline access to ADS (Astrophysical Data System)

=head1 SYNOPSIS

Make the F<ads> file executable and put it on your execution path.

  ads [options] [author]... [year] [endyear]

=head1 DESCRIPTION

B<ads> is a commandline tool to pass a query to the website of the
Astrophysical Data System (ADS). The tool constructs a query URL and
sends it to the default web browser. B<ads> takes author names and
publishing years from the command line with as little fuss as
possible. Additional search fields and options can be specified using
command line switches, which also is a lot faster than the web form.

Alphabetic arguments are parsed as author names. Quotes are only
necessary to protect whitespace inside a name. Alternatively, replace
spaces with underscore C<_> characters. A first name can be added like
C<first.last> (separated by dot) or C<last,first> (separated by
comma). Only the initial letter of the first name is significant, so
C<last,f> and C<last,first> are equivalent.

Numerical arguments are interpreted as publishing years. Single or
two-digit years are moved into the 20th and 21st century under the
assumption that the specified year is intended to be at most 1 year
into the future. A second year-like argument or something like
'2012-2014' specifies a range. A year ending with `-` means starting
from that year.

=head1 OPTIONS

=over 5

=item B<-t> STRING, B<-a> STRING, B<-f> STRING   

String phrase to be matched in the I<title>, I<abstract>, or
I<fulltext>, respectively, of a bibliographic source.  Multiple
B<-t>/B<-a>/B<-f> switches with strings can be given to retrieve only
sources that match all requested strings.

=item B<-o> OBJECT

An astronomical object to search for. Quote OBJECT to protect
whitespace, or replace spaces with underscore characters.

=item B<-i> ORCID

Search for an author by ORCID identifier. Leading zeros in the ORCID
can be left out.

=item B<-c>

Sort matched bibliographic sources by citation count.  The default is
to sort by date. B<-c> is a shorthand for B<-sc>, see below.

=item B<-r>

List only refereed sources.

=item B<-A> B<-P> B<-G>

Narrow to I<astronomy>, I<physics>, or I<general> database,
respectively.

=item B<-s> SORTING

Sorting mode for matched entries. The mode can be given as a single
letter, in full, or abbreviated.

  d  => date                  # This is the default
  a  => first_author          # abbreviations: fa
  c  => citation_count        # abbreviations: cc
  n  => citation_count_norm   # abbreviations: cn ccn nc ncc
  s  => score

=item B<-d>

Print debugging information. This needs to be the first command line
argument to be effective.

=back

=head1 EXAMPLES

Get papers by Dullemond and Dominik written in 2004.

    ads Dullemond Dominik,C 2004

Same authors, but only the papers where Dullemond is first author, and
in the range from 2000 to 2004.

    ads -r ^Dullemond Dominik 2000 2004
    ads -r ^Dullemond Dominik 2000-2004
    ads -r ^Dullemond Dominik 0-4

Get papers of Ed van den Heuvel, a name with spaces that need to be
protected.

    ads "van den heuvel,E"
    ads van_den_heuvel,E

Papers by Antonella Natta, sorted by normalized citations.

    ads -sn a.natta

B<ads> allows to freely mix switch arguments with author and year
arguments, because additional constraints sometimes present themselves
while constructing the query.

    ads natta,a -sn 1990 2000 -t protostar

Find articles with the phrase "planet formation" in the abstract.

    ads -a "planet formation"

Find articles with both "planet" and "system" anywhere in the
abstract.

    ads -aplanet -a system

=head1 AUTHOR

Carsten Dominik    <dominik.dominik@gmail.com>

This program is free software. It it released under the same rules as
Perl itself, so wither the GNU General Public License, or the Artistic
License.

=cut
