=pod

=head1 NAME

B<ads> - commandline access to ADS (Astrophysical data system)

=head1 SYNOPSIS

ads [options] author [author2]... [startyear] [endyear]

=head1 DESCRIPTION

B<ads> is a commandline tool to pass a query to the website of the
Astrophysical data system (ADS). The tool will construct a query and
send it to the default web browser.  B<ads> takes author names and
publishing years from the command line with as little fuss as
possible. Some search parameters can be changed with command line
switches.

The main reason for writing this tool is that the author intensely
dislikes filling web forms on a regular basis.

Arguments containing letters are parsed as author names. Necessary
spaces in author names can be given as underscores `_`, or you can put
the name in quotes. To be more specific than just a lastname, you can
specify a first name like first.last (separated by dot) or last,first
(separated by comma).  Only the initial letter of the first name is
significant, so last,f and last,first are equivalent.

Arguments that are numbers are parsed as publishing year. Single or
two-digit years are interpeted as years in the 20th and 21st century
under the assumption that years are in the past, not in the future.  A
second year-like argument or something like '2012-2014' specifies a
range. A year ending with `-` means starting from that year.

=head1 OPTIONS

=over 5

=item B<-t> STRING

A string to put into the title search field.

=item B<-a> STRING

A string to put into the abstract search field.

=item B<-f> STRING

A string to put into the fulltext search field.

=item B<-s> SORTING

Sorting mode for matched entries.  DEFAULT is 'date', to sort by date.
Values can be given in full, or be abbreviated.  The allowed values
and abbreviations are:
 
   d              => date                       This is the default
   a  fa          => first_author
   c  cc          => citation_count
   cn ccn nc ncc  => citation_count_norm
   s              => score

=item B<-r>

Only list refereed sources.  Default is to list also unrefereed.

=item B<-d>

Print debugging information

=back

=head1 EXAMPLES

Get papers by Dullemond and Dominik written in 2004.

    ads Dullemond Dominik,C 2004

Same authors, but only the papers where Dullemond is first author, and
in the range from 2000 to 2004.  Note the two ways to specify a range.

    ads -r ^Dullemond Dominik 2000 2004
    ads -r ^Dullemond Dominik 2000-2004

Get papers of Ewine van Dishoeck.  This example shows that spaces in
name field can be replaced by the underscore character, if you don't
want to quote the name.

    ads "van dishoeck,E"
    ads van_dishoeck,E

Papers by Alexander Tielens, sorted by normalized citations.

    ads -scn tielens,a

For fun, and because I often think of additional constraints only after
I have typed the names, this command also allows to give the switch
arguments after or mixed with the author and year arguments.

    ads tielens,a -t interstellar 1979 -scc 1980

=head1 AUTHOR

Carsten Dominik    <dominik.dominik@gmail.com>

This program is free software.  It it released under the rules like
Perl itself, so wither the GNU General Public License, or the Artistic
License.

=cut
